### ISSUE TITLE
Request for Pre-trained Model Weights

### ISSUE THREAD

**Issue by zoule41** [SZUHvern/MaCo#1]
Hello,

 I am reaching out to express my interest in your project, MaCo. I have been following your work and am impressed by the results and potential applications of your model.

I am currently working on a project that is closely related to your research, and I believe that having access to your pre-trained model weights could significantly enhance our work and help us achieve better results. Therefore, I kindly request if you could share the pre-trained model weights with me.

I understand the effort and resources that go into training such models, and I assure you that the weights will be used solely for research purposes. I also commit to citing your work and giving proper acknowledgment in any publications or presentations that result from the use of your model.

Please let me know if there are any terms or conditions for using the model weights. I am more than willing to comply with any requirements you may have.

Thank you for considering my request. I look forward to the possibility of collaborating with you and contributing to the advancement of this field.

**Comment by SZUHvern** [comment]
Thank you for your interest in our work! 
We'll update the repository after our manuscript is formally accepted.
